author:
  name: charlotte mach
  url: charlottemach.github.io

title: charlotte mach
description: 'Knows how to google all the things, debugger of many clouds, somewhat German, likes cookies and containers.'
contact: 'Talk to me on <a href="https://twitter.com/tinydata0" target="_blank">twitter</a> or via <a href=mailto:charlotte.mach@fs.lmu.de target="_blank">email</a>.'

markdown: kramdown

plugins_dir:
  - jekyll-paginate-v2

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

permalink: /:year/:month/:title.html

url:              http://charlottemach@github.io
baseurl:          /

