# Adapted from https://github.com/JamesIves/github-pages-deploy-action
name: Build and Deploy Scroll
on:
  push:
    branches:
      - main
      - scroll
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          npm install scroll-cli
          npm install -g marked
          ./node_modules/scroll-cli/scroll.js build
          rm .gitignore
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: scroll-output # The branch the action should deploy to.
          folder: .
